"""Generate negotiated capture-v3 types, payload schemas, and compatibility manifest."""
from pathlib import Path
import json,subprocess,hashlib,argparse
from catalog_preview_contract import ts
from ingestion_contract import require_version_change
ROOT=Path(__file__).resolve().parents[1];BUNDLE=ROOT/'contracts/capture';VERSION='1.2.0'
def outputs():
 raw=subprocess.run(['cargo','run','--quiet','--locked','-p','nexofolio-contracts','--example','capture_schema'],cwd=ROOT,capture_output=True,text=True,check=True)
 schemas=json.loads(raw.stdout);old=json.loads((ROOT/'contracts/ingestion/batch.schema.json').read_text())
 b=schemas['batch.schema.json'];b['properties']['schema_version']={'const':'3'};b['properties']['records'].update(minItems=1,maxItems=50);b['properties'].pop('service_key',None);b.get('required',[]).remove('service_key') if 'service_key' in b.get('required',[]) else None
 record=schemas['record.schema.json'];record['properties']['payload_version']={'const':'1'};record['properties']['captured_at']['format']='date-time'
 kinds={'http_exchange':'HttpExchange','page_context':'PageContextPayload','interaction':'InteractionPayload','ui_snapshot':'UiSnapshotPayload','image_reference':'ImageReferencePayload'}
 defs=record.setdefault('$defs',{});defs.update({k:v for k,v in old['$defs'].items() if k!='Record'})
 for name,doc in list(schemas.items()):
  if name in ['page-context.schema.json','interaction.schema.json','ui-snapshot.schema.json','image-reference.schema.json']:
   defs.update(doc.get('$defs',{}));defs[doc['title']]={k:v for k,v in doc.items() if k not in ['$schema','$defs']}
 record['allOf']=[{'if':{'properties':{'kind':{'const':kind}}},'then':{'properties':{'payload':{'$ref':'#/$defs/'+typ}}}} for kind,typ in kinds.items()]
 record['allOf'].append({'if':{'properties':{'kind':{'enum':['page_context','interaction','ui_snapshot','image_reference']}}},'then':{'required':['context'],'properties':{'context':{'$ref':'#/$defs/CaptureContext'}}}})
 schemas['receipt.schema.json']['properties']['schema_version']={'const':'3'}
 defs_all={}
 for schema in schemas.values():
  for name,value in schema.get('$defs',{}).items():
   if name in defs_all and defs_all[name]!=value:raise ValueError('conflicting definition '+name)
   defs_all[name]=value
 types='// Generated by scripts/capture_contract.py; validate payloads against their Schema.\n'
 for name,value in sorted(defs_all.items()):types+='export type '+name+' = '+ts(value)+';\n'
 for name,schema in schemas.items():
  title=schema['title']
  if title not in defs_all:types+='export type '+title+' = '+ts(schema)+';\n'
 result={name:json.dumps(value,ensure_ascii=False,indent=2)+'\n' for name,value in schemas.items()};result['types.generated.ts']=types
 hashes={name:hashlib.sha256(value.encode()).hexdigest() for name,value in result.items()};hashes['behavior.md']=hashlib.sha256((BUNDLE/'behavior.md').read_bytes()).hexdigest()
 result['manifest.json']=json.dumps({'contract_version':VERSION,'schema_version':'3','files':hashes},indent=2)+'\n';return result
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');p.add_argument('--base-ref');a=p.parse_args();generated=outputs()
 if a.base_ref and set(a.base_ref)!={'0'}:
  old=subprocess.run(['git','show',a.base_ref+':contracts/capture/manifest.json'],cwd=ROOT,capture_output=True,text=True)
  if old.returncode==0:require_version_change(json.loads(old.stdout),json.loads(generated['manifest.json']))
 for name,text in generated.items():
  target=BUNDLE/name
  if a.check:
   if not target.exists() or target.read_text()!=text:raise SystemExit('Capture contract drift: '+name)
  else:target.write_text(text)
 print('Capture contract '+('verified' if a.check else 'generated'))
