"""Generate/check the Rust-owned catalog preview contract and prompt manifest."""
from pathlib import Path
import argparse,subprocess,json,hashlib
from ingestion_contract import require_version_change
ROOT=Path(__file__).resolve().parents[1]
BUNDLE=ROOT/'contracts/catalog-preview'
VERSION='1.4.0'
def ts(s):
 if isinstance(s,bool):return "unknown" if s else "never"
 if '$ref' in s:return s['$ref'].split('/')[-1]
 if 'const' in s:return json.dumps(s['const'])
 if 'enum' in s:return ' | '.join(json.dumps(v) for v in s['enum'])
 if 'anyOf' in s:return ' | '.join(ts(v) for v in s['anyOf'])
 if 'oneOf' in s:return ' | '.join(ts(v) for v in s['oneOf'])
 kind=s.get('type')
 if isinstance(kind,list):return ' | '.join(ts(dict(s,type=k)) for k in kind)
 if kind=='object':
  if 'properties' not in s:return '{ [key: string]: unknown }'
  required=s.get('required',[])
  return '{ '+ '; '.join(json.dumps(k)+('' if k in required else '?')+': '+ts(v) for k,v in s['properties'].items())+' }'
 if kind=='array':
  if 'prefixItems' in s:return '['+', '.join(ts(x) for x in s['prefixItems'])+']'
  return '('+ts(s.get('items',{}))+')[]'
 return {'string':'string','integer':'number','number':'number','boolean':'boolean','null':'null'}.get(kind,'unknown')

def generated():
 result=subprocess.run(['cargo','run','--quiet','--locked','-p','nexofolio-contracts','--example','catalog_preview_schema'],cwd=ROOT,capture_output=True,text=True,check=True)
 schemas={name:json.dumps(value,ensure_ascii=False,indent=2)+'\n' for name,value in json.loads(result.stdout).items()}
 definitions={}
 parsed=json.loads(result.stdout)
 for schema in parsed.values():
  for name,value in schema.get('$defs',{}).items():
   if name in definitions and definitions[name]!=value:raise ValueError('conflicting schema definition: '+name)
   definitions[name]=value
 types='// Generated by scripts/catalog_preview_contract.py; validate responses against JSON Schema.\n'
 for name,value in sorted(definitions.items()):types+='export type '+name+' = '+ts(value)+';\n'
 for filename,name in [('page.schema.json','CatalogPreviewPage'),('detail.schema.json','CatalogPreviewDetail'),('official.schema.json','OfficialCatalog'),('official-interfaces.schema.json','OfficialInterfacePage'),('versions.schema.json','CatalogVersionPage'),('publish.schema.json','PublishCatalog'),('restore.schema.json','RestoreCatalog'),('activation.schema.json','CatalogActivation')]:types+='export type '+name+' = '+ts(parsed[filename])+';\n'
 schemas['types.generated.ts']=types
 files={name:hashlib.sha256(content.encode()).hexdigest() for name,content in schemas.items()}
 files.update({name:hashlib.sha256((BUNDLE/name).read_bytes()).hexdigest() for name in ['behavior.md','prompt.txt']})
 schemas['manifest.json']=json.dumps({'contract_version':VERSION,'files':dict(sorted(files.items()))},indent=2)+'\n'
 return schemas
if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');parser.add_argument('--base-ref');args=parser.parse_args()
 outputs=generated()
 if args.base_ref and set(args.base_ref)!={'0'}:
  old=subprocess.run(['git','show',args.base_ref+':contracts/catalog-preview/manifest.json'],cwd=ROOT,capture_output=True,text=True)
  if old.returncode==0:require_version_change(json.loads(old.stdout),json.loads(outputs['manifest.json']))
 for name,content in outputs.items():
  target=BUNDLE/name
  if args.check:
   if not target.exists() or target.read_text()!=content:raise SystemExit('Catalog preview contract drift: '+name)
  else:target.write_text(content)
 print('Catalog preview contract '+('verified' if args.check else 'generated'))
