"""Generate/check document response types and package manifest from its authoritative schema."""
from pathlib import Path
import json,hashlib,argparse,subprocess
from ingestion_contract import require_version_change
from catalog_preview_contract import ts
ROOT=Path(__file__).resolve().parents[1]/'contracts/documents'
def outputs():
 schema=json.loads((ROOT/'responses.schema.json').read_text())
 extra=json.loads(subprocess.run(['cargo','run','--quiet','--locked','-p','nexofolio-contracts','--example','assessment_schema'],cwd=ROOT.parents[1],capture_output=True,text=True,check=True).stdout)
 definitions=dict(schema['$defs'])
 result={name:json.dumps(value,ensure_ascii=False,indent=2)+'\n' for name,value in extra.items()}
 for value in extra.values():
  for name,definition in {**value.get('$defs',{}),value['title']:{k:v for k,v in value.items() if k not in ('$schema','$defs','title')}}.items():
   if name in definitions and definitions[name]!=definition:raise ValueError('conflicting definition '+name)
   definitions[name]=definition
 types='// Generated by scripts/document_contract.py; validate runtime responses against the Schema.\n'
 for name,value in definitions.items():types+='export type '+name+' = '+ts(value)+';\n'
 files={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(ROOT.iterdir()) if p.name in ['responses.schema.json','behavior.md']}
 files.update({name:hashlib.sha256(value.encode()).hexdigest() for name,value in result.items()})
 files.update({str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted((ROOT/'fixtures').glob('*.json'))})
 manifest={'contract_version':'2.2.0','files':files,'types_sha256':hashlib.sha256(types.encode()).hexdigest()}
 result.update({'types.generated.ts':types,'manifest.json':json.dumps(manifest,indent=2)+'\n'})
 return result

if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');parser.add_argument('--base-ref');args=parser.parse_args()
 if args.base_ref and set(args.base_ref)!={'0'}:
  result=subprocess.run(['git','show',args.base_ref+':contracts/documents/manifest.json'],cwd=ROOT.parents[1],capture_output=True,text=True)
  if result.returncode==0:
   try:require_version_change(json.loads(result.stdout),json.loads(outputs()['manifest.json']))
   except ValueError as e:raise SystemExit(str(e))
 for name,content in outputs().items():
  p=ROOT/name
  if args.check:
   if not p.exists() or p.read_text()!=content:raise SystemExit(f'Document contract drift: {name}')
  else:p.write_text(content)
 print('Document contract verified' if args.check else 'Document contract generated')
