"""Build/check the portable ingestion contract bundle; no third-party runtime required.
Schema is authoritative; generated TypeScript and hashes are checked into both consumers.
"""
from pathlib import Path
import argparse,hashlib,json,subprocess
CONTRACT_VERSION='2.2.0'
ROOT=Path(__file__).resolve().parents[1]/'contracts/ingestion'

def ts(s):
 if 'const' in s:return json.dumps(s['const'])
 if '$ref' in s:return s['$ref'].split('/')[-1]
 if 'enum' in s:return ' | '.join(json.dumps(v) for v in s['enum'])
 if 'anyOf' in s:return ' | '.join(ts(x) for x in s['anyOf'])
 kind=s.get('type')
 if kind=='object':
  if 'properties' not in s:return '{ [key: string]: unknown }'
  req=s.get('required',[])
  return '{ '+ '; '.join(json.dumps(k)+('' if k in req else '?')+': '+ts(v) for k,v in s.get('properties',{}).items())+' }'
 if kind=='array':
  if 'prefixItems' in s:return '['+', '.join(ts(x) for x in s['prefixItems'])+']'
  return '('+ts(s['items'])+')[]'
 return {'string':'string','integer':'number','number':'number','boolean':'boolean','null':'null'}.get(kind,'unknown')

def outputs():
 batch=json.loads((ROOT/'batch.schema.json').read_text());receipt=json.loads((ROOT/'receipt.schema.json').read_text())
 generated='// Generated by scripts/ingestion_contract.py; do not edit. Runtime Schema validation is still required.\n'
 for name,value in batch['$defs'].items(): generated+='export type '+name+' = '+ts(value)+';\n'
 generated+='export type IngestionCapabilities = '+ts(json.loads((ROOT/'capabilities.schema.json').read_text()))+';\n'
 for filename,typename in [('environment.schema.json','ProjectEnvironment'),('environment-page.schema.json','EnvironmentPage'),('environment-write.schema.json','EnvironmentWrite')]:
  generated+='export type '+typename+' = '+ts(json.loads((ROOT/filename).read_text()))+';\n'
 generated+='export type IngestionBatch = '+ts(batch)+';\nexport type BatchReceipt = '+ts(receipt)+';\n'
 files=sorted(ROOT.glob('*.schema.json'))+sorted((ROOT/'fixtures').glob('*.json'))+[ROOT/'behavior.md']+sorted((ROOT/'legacy').rglob('*.*'))
 hashes={str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in files}
 manifest={'contract_version':CONTRACT_VERSION,'schema_version':'2','supported_payloads':{'http_exchange':['1']},'files':hashes,'types_sha256':hashlib.sha256(generated.encode()).hexdigest()}
 return {'types.generated.ts':generated,'manifest.json':json.dumps(manifest,indent=2)+'\n'}
def require_version_change(old,new):
 if old!=new and old['contract_version']==new['contract_version']:
  raise ValueError('Contract changed without a version bump')

if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');parser.add_argument('--base-ref');args=parser.parse_args()
 if args.base_ref and set(args.base_ref)!={'0'}:
  result=subprocess.run(['git','show',args.base_ref+':contracts/ingestion/manifest.json'],capture_output=True,text=True,cwd=ROOT.parents[1])
  if result.returncode==0:
   old=json.loads(result.stdout);new=json.loads(outputs()['manifest.json'])
   try:require_version_change(old,new)
   except ValueError as exc:raise SystemExit(str(exc))
 for name,content in outputs().items():
  p=ROOT/name
  if args.check:
   if not p.exists() or p.read_text()!=content:raise SystemExit(f'Contract drift: regenerate {p.name}')
  else:p.write_text(content)
 print('Ingestion contract bundle '+('verified' if args.check else 'generated'))
