from pathlib import Path
import subprocess,json,hashlib,argparse
from catalog_preview_contract import ts
from ingestion_contract import require_version_change
ROOT=Path(__file__).resolve().parents[1];BUNDLE=ROOT/'contracts/maintenance';VERSION='1.5.0'
def outputs():
 p=subprocess.run(['cargo','run','--quiet','--locked','-p','nexofolio-contracts','--example','maintenance_schema'],cwd=ROOT,capture_output=True,text=True,check=True);schemas=json.loads(p.stdout);defs={}
 for s in schemas.values():
  for name,value in s.get('$defs',{}).items():
   if name in defs and defs[name]!=value:raise ValueError('conflicting definition '+name)
   defs[name]=value
 types='// Generated by scripts/maintenance_contract.py; validate against JSON Schema.\n'
 for name,value in sorted(defs.items()):types+='export type '+name+' = '+ts(value)+';\n'
 for s in schemas.values():
  if s['title'] not in defs:types+='export type '+s['title']+' = '+ts(s)+';\n'
 out={name:json.dumps(s,ensure_ascii=False,indent=2)+'\n' for name,s in schemas.items()};out['types.generated.ts']=types;hashes={name:hashlib.sha256(v.encode()).hexdigest() for name,v in out.items()};hashes['behavior.md']=hashlib.sha256((BUNDLE/'behavior.md').read_bytes()).hexdigest();out['manifest.json']=json.dumps({'contract_version':VERSION,'files':hashes},indent=2)+'\n';return out
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');p.add_argument('--base-ref');a=p.parse_args();out=outputs()
 if a.base_ref and set(a.base_ref)!={'0'}:
  prior=subprocess.run(['git','show',a.base_ref+':contracts/maintenance/manifest.json'],cwd=ROOT,capture_output=True,text=True)
  if prior.returncode==0:require_version_change(json.loads(prior.stdout),json.loads(out['manifest.json']))
 for name,value in out.items():
  path=BUNDLE/name
  if a.check:
   if not path.exists() or path.read_text()!=value:raise SystemExit('Maintenance contract drift: '+name)
  else:path.write_text(value)
 print('Maintenance contract '+('verified' if a.check else 'generated'))
